version: '3.8'

services:
  app:
    container_name: store-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - store-network

networks:
  wsb-network:
    driver: bridge
